--- 
version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper.backup-s3
    network_mode: host
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka.backup-s3
    network_mode: host
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  cp-kafka-rest:
    image: confluentinc/cp-kafka-rest
    container_name: kafka-rest.backup-s3
    network_mode: host
    ports:
      - 8082:8082
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_REST_HOST_NAME: localhost
    extra_hosts:
      - "moby:127.0.0.1"
  
  kafka-topics-ui:      
    image: landoop/kafka-topics-ui
    container_name: kafka-topics-ui.backup-s3
    network_mode: host
    ports:
      - 8000:8000
    depends_on:
      - cp-kafka-rest
    environment:
      KAFKA_REST_PROXY_URL: "http://localhost:8082"
      PROXY: "true"
      PORT: 8000
    extra_hosts:
      - "moby:127.0.0.1"
  
  kafka-connect:
    image: confluentinc/cp-kafka-connect
    container_name: kafka-connect.backup-s3
    network_mode: host
    environment: 
      CONNECT_BOOTSTRAP_SERVERS: localhost:9092
      CONNECT_GROUP_ID: kafka-connect
      CONNECT_CONFIG_STORAGE_TOPIC: kafka-connect.config
      CONNECT_OFFSET_STORAGE_TOPIC: kafka-connect.offsets
      CONNECT_STATUS_STORAGE_TOPIC: kafka-connect.status
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: localhost
      CONNECT_REST_HOST_NAME: localhost
      CONNECT_ZOOKEEPER_CONNECT: localhost:2181
    depends_on:
      - zookeeper
      - kafka
    ports: 
      - 8083:8083
    volumes:
      - "./jars:/etc/kafka-connect/jars"
      - "./aws:/root/.aws"
      - "./files:/files"
  
  kafka-connect-ui: 
    network_mode: host
    environment: 
      CONNECT_URL: "http://localhost:8083"
      PORT: 8001
    image: landoop/kafka-connect-ui
    container_name: kafka-connect-ui.backup-s3
    ports:
      - 8001:8001

  
  minio:
    image: minio/minio
    container_name: minio.backup-s3
    #network_mode: host
    ports:
      - 9000:9000
    command: ["minio", "server", "/data"]
    volumes:
      - "./minio-data:/data"
