= Kafka backup/restore with S3
:sectnums:
:toc:

== Описание
Пример выполнения backup/restore топиков Kafka в хранилище с интерфейсом S3.

В качестве S3 используется opensource решение link:https://www.minio.io/[minio].

Ядро реализации транспорта - Kafka Connect.

Реализация коннектора от spredfast link:https://github.com/spredfast/kafka-connect-s3/[kafka-connect-s3].

Для развертывания инфраструктуры используется link:https://docs.docker.com/compose/[docker-compose].

В качестве основы использована статья link:https://jobs.zalando.com/tech/blog/backing-up-kafka-zookeeper/[Backing up Apache Kafka and Zookeeper to S3].


== Практика
=== Создание контента и backup

==== Запуск

[source,bash]
docker-conpose up -d

Будут подняты следующие контейнеры:

* zookeeper - распределенное key-value хранилище, используется kafka.
* kafka - распределенный брокер сообщений.
* kafka-rest - необходим для kafka-topics-ui
* kafka-topics-ui - предоставляет web интерфейс для мониторинга топаков
* kafka-connect - фреймворк интеграции Kafka с другими системами
* kafka-connect-ui -  web интерфейс для мониторинга connector kafka-connect
* minio - opensource объектное хранилище с интерфейсом S3.

==== Создать топик

[source,bash]
kafka-topics --create --topic example-topic --replication-factor 1 --partitions 1  --zookeeper localhost:2181

_Created topic "example-topic"._

==== Наполнить контентом
[source,bash]
kafka-console-producer --topic example-topic --broker-list localhost:9092 < hello world

==== Наличие контента можно проверить
* в UI http://localhost:8000/#/cluster/default/topic/n/example-topic/
* либо через CLI
[source,bash]
kafka-console-consumer --topic example-topic --bootstrap-server localhost:9092 --from-beginning

==== Создать bucket в minio "example-kafka-backup-bucket".
Использовал UI minio (см. раздел Интерфейсы и доступы).

==== Создать credentials для aws в директории aws/credentials:
* link:https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-file-format[документация].
* link:https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html[Альтернативные варианты] (не проверял)

==== Создать connector.
curl -v -d @example-topic-backup-tasks.json -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8083/connectors

Коннектор прочитает сообщения из топика example-topic в соответствии со своим конфигом и создаст архивную запись в minio.
[NOTE]
В текущей версии коннектора есть конфликт с реализацией minio: коннектор после записи возвращает ошибку несоответствия хэш. Пересборка коннекторов с использованием последней 1.11.336 версии aws-java-sdk-s3 ошибку не исправила. Однако запись происходит и доступна для дальнейшего восстановления.

=== Восстановление

==== Остановить кластер. Сэмулировать удаление данных.
[source,bash]
docker-compose down
docker rm kafka.backup-s3

==== Поднять стек
[source,bash]
docker-compose up -d

[NOTE]
Поскольку kafka-connector хранит конфиги коннекторов в виде записей в топиках (похоже на event sourcing), то после удаления данных kafka список коннекторов будет пуст.

==== Создать коннектор восстановления
[source,bash]
curl -v -d @example-restore.json -H "Content-Type: application/json" -H "Accept: application/json" http://localhost:8083/connectors

==== Проверить наличие записей в топике example-topic
[source,bash]
kafka-console-consumer --topic example-topic --from-beginning --bootstrap-server localhost:9092

либо в ui http://localhost:8000/#/cluster/default/topic/n/example-topic/


=== Топики с ключами

Дополнительно можно проверить работу резервирования топиков с ключами. Для этого созданы шаблоны коннекторов топика kafka-connect.config:

* kafka-connect-topic-backup-tasks.json
* kafka-connect-topic-restore.json

== Резюме
.преимущества подхода:
* возможно выполнять опреации backup без остановки кластера;
* умеет работать с ключами;
* использует операции сжатия;

.недостатки:
- требует отедльного ПО с интерфейсом S3 (minio);
- необходимо также резервировать minio;
- ошибки, связанные с несовместимостью интерфейсов minio и библиотек aws.


== Интерфейсы и доступы
топики: http://localhost:8000/
connectors: http://localhost:8001
minio: http://localhost:9000/minio
учетка:
[source,bash]
docker logs minio.backup-s3|grep -A2 AccessKey
